<?php

/**
 * @file
 * Provide structure for the drupal challenge module.
 */

include_once 'drupal_challenge.features.inc';

/**
 * Implements hook_form_alter().
 */
function drupal_challenge_form_alter(&$form, &$form_state, $form_id) {

  // Check if in the job form.
  if($form_id == 'job_node_form' && $node = $form_state['node']) {
   // Check if in edit form and value is freelance. 
   if (isset($node->nid) && $node->field_employment_type[LANGUAGE_NONE][0]['value'] == 'Freelance') {
     $form['field_employment_type']['#disabled']= TRUE;
   }
  }
}
